 driver file name is 
 ../WORK/quickuseF77_v1.18.nml                                                  
                                          
 output file name is 
 junk.dat                                                                       
                                          
 jacob file name is 
 junk.jac                                                                       
                                          
 checking parameters in kcarta.param
   
 Max #of atmospheres from *RADFIL =            8
 Max #of gases from *GAS/XSCFIL =           80
 Max #of mixed paths *MIXFIL =          200
   
 checking parameters (from *PARAMS) .... 
   
 Reading in the Namelists ............. 
 successfully read in params .....
 default | final | diff override params
 ---------------------------------------
iI =  1
          -1          -1           0
           1           1           0
           2           2           0
           1           1           0
           5           5           0
           1           1           0
          -1          -1           0
          -1           1          -2
           2           2           0
       -9999       -9999           0
 ---------------------------------------
iI =  2
          -1          -1           0
           3           3           0
           0           0           0
          -1          -1           0
           0           0           0
           1           1           0
          -1          -1           0
           1           1           0
          -1          -1           0
           5           5           0
 ---------------------------------------
iI =  3
          -1          -1           0
           1           1           0
          -1          -1           0
       -9999          -1       -9998
       -9999          -1       -9998
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
 ---------------------------------------
iI =  4
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
       -9999       -9999           0
 ---------------------------------------
 checking parameters (from *PARAMS) .... 
   
 **********************************************************************
 successfully read in freqs .....
 **********************************************************************
 successfully read in molgas .....
 **********************************************************************
 successfully read in xscgas .....
 **********************************************************************
 successfully read in prfile .....
 **********************************************************************
 successfully read in weight .....
 **********************************************************************
atm#   1 raAtmLoop raSatHeight =     -1.000reset to 705 km
 successfully read in radnce .....
 **********************************************************************
 successfully read in jacobn .....
 **********************************************************************
 successfully read in spectra .....
 **********************************************************************
 successfully read in nonlte .....
 **********************************************************************
 successfully read in scattr .....
 **********************************************************************
 successfully read in output .....
 **********************************************************************
 successfully read in endinp .....
 **********************************************************************
 checking parameters (from *PARAMS) .... 
   
 successfully checked params .....
kActualJacs,kActualJacsB,kActualJacsT =  -1 -1 -1
 **********************************************************************
 successfully checked freqs .....
 **********************************************************************
 including all lbl gases from 1 to           42
  plus 101,102,103 for Self,Forn cont, heavy water
 Fatal Error found : closing all units ..
 bad luck ... emergency exit!
