% this is in /home/sergio/KCARTA/WORK/RUN_TARA/GENERIC_RADSnJACS_MANYPROFILES/JUNK/AIRS_gridded_Dec2021_startSept2002_trendsonly/mv_latbin32_timeseries.m

% see /home/sergio/KCARTA/WORK/RUN_TARA/GENERIC_RADSnJACS_MANYPROFILES/set_rtp.m
%   use_this_rtp = '/home/sergio/MATLABCODE/oem_pkg_run/FIND_NWP_MODEL_TRENDS/SimulateTimeSeries/simulate64binsERA5_32.rp.rtp'; 
% which was generated by code 
%%  /home/sergio/MATLABCODE/oem_pkg_run/AIRS_gridded_STM_May2021_trendsonlyCLR/SyntheticTimeSeries_ERA5_AIRSL3_CMIP6/driver_check_WV_T_RH_ERA5_geo_and_spectral_rates2.m

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% move the files made by kCARTA into subdirs separetd by lonbin (1:72)
%{
for ii = 1 : 72
  ind = (1:72:16416) + (ii-1);
  mker = ['!/bin/mkdir ERA5_LATBIN32_72lonbinsx228timesteps/Lonbin' num2str(ii,'%02d')];
  eval(mker);
  for jj = 1 : length(ind)
    mver = ['!/bin/mv ../individual_prof_convolved_kcarta_airs_' num2str(ind(jj)) '.mat ERA5_LATBIN32_72lonbinsx228timesteps/Lonbin' num2str(ii,'%02d') '/.' ]; 
    fprintf(1,'%2i : %s \n',ii,mver);
    eval(mver);
  end
end
%}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

addpath /asl/matlib/aslutil
%% now load in the files and put togeher the time series for each lonbin
for ii = 1 : 72  
  clear raaData
  ind = (1:72:16416) + (ii-1);
  for jj = 1 : length(ind)
    fin = ['ERA5_LATBIN32_72lonbinsx228timesteps/Lonbin' num2str(ii,'%02d') '/individual_prof_convolved_kcarta_airs_' num2str(ind(jj)) '.mat'];
    x = load(fin);
    raaData(:,jj) = x.rKc;
  end
  fKc = x.fKc;
  i1231 = find(fKc >= 1231,1);
  comment = 'see /home/sergio/KCARTA/WORK/RUN_TARA/GENERIC_RADSnJACS_MANYPROFILES/JUNK/AIRS_gridded_Dec2021_startSept2002_trendsonly/mv_latbin32_timeseries.m';
  saver = ['save ERA5_LATBIN32_72lonbinsx228timesteps/timeseries_latbin32_lonbin' num2str(ii,'%02d') '.mat raaData fKc comment'];
  eval(saver);
  plot(1:228,rad2bt(1231,raaData(i1231,:))); title(num2str(ii)); pause(0.1);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp('now figure out the spectral trends!')
