### /usr/ebuild/software/GCCcore/11.2.0/bin/gfortran --> /usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   basic_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   ttorad_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   spline_and_sort_and_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   freqfile.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   s_misc.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   s_writefile.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeff_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   clear_scatter_basic.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_nonlte_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_mr_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_gas_wt_spectra.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_pth_mix.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_rad_jac_scat.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_output.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_layers.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_layers_lblrtm.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_misc.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   datetime_module.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   solar_insolation.f90
#ifort    -c -I/home/sergio/git/rtp/rtpV201/include -fpp -implicitnone -msse2 -extend-source 132 -O2 -names lowercase -assume nounderscore -heap-arrays -diag-disable 8291 -mcmodel=medium -shared-intel   n_rtp.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   n_duplicate_sky.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure    n_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeffSPL.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeffSPLJAC.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeff_FAST_details.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeff_FAST_details2.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeff_FAST.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcont_xsec.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcoeffMAIN.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_angles.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_misc.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_diff_and_quad.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_common.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_up.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_down.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_limb.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_flux.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   rad_limb.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   clear_scatter_misc.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   klineshapes.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcousin.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   klinemix.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kvoigt_cousin.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kreadVTprofiles.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kbloat.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kpredictVT.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   knonlte.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   singlescatter.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_pclsam_up.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   jac_pclsam_down.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_rtspec_code.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_rtspec_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_rtspec_flux.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_pclsam_code.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_pclsam_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_pclsam_flux.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_graycld_code.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_graycld_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_disort_aux.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   -freal-4-real-8  scatter_disort_code.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_disort_flux.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_disort_main.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   scatter_interface.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcartamisc.f90
/usr/ebuild/installs/software/GCCcore/12.3.0/bin/gfortran -c -ffixed-line-length-none -fdec-structure   kcartamain.f90
