
SHELL = /bin/sh

TEXHOME = /salsify/packages/teTeX/bin/
TEXHOME = /usr/bin/

all: kcarta1.14.ps bkcarta1.10.ps ReadMeFirst.ps

kcarta1.18.ps: kcarta1.18.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.18.tex && \
	$(TEXHOME)latex kcarta1.18.tex && \
	$(TEXHOME)dvips -f kcarta1.18.dvi > kcarta1.18.ps

kcarta1.16.ps: kcarta1.16.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.16.tex && \
	$(TEXHOME)latex kcarta1.16.tex && \
	$(TEXHOME)dvips -f kcarta1.16.dvi > kcarta1.16.ps

kcarta1.15.ps: kcarta1.15.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.15.tex && \
	$(TEXHOME)latex kcarta1.15.tex && \
	$(TEXHOME)dvips -f kcarta1.15.dvi > kcarta1.15.ps

kcarta1.14.ps: kcarta1.14.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.14.tex && \
	$(TEXHOME)latex kcarta1.14.tex && \
	$(TEXHOME)dvips -f kcarta1.14.dvi > kcarta1.14.ps

kcarta1.12.ps: kcarta1.12.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.12.tex && \
	$(TEXHOME)latex kcarta1.12.tex && \
	$(TEXHOME)dvips -f kcarta1.12.dvi > kcarta1.12.ps

kcarta1.11.ps: kcarta1.11.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.11.tex && \
	$(TEXHOME)latex kcarta1.11.tex && \
	$(TEXHOME)dvips -f kcarta1.11.dvi > kcarta1.11.ps

kcarta1.10.ps: kcarta1.10.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.10.tex && \
	$(TEXHOME)latex kcarta1.10.tex && \
	$(TEXHOME)dvips -f kcarta1.10.dvi > kcarta1.10.ps

bkcarta1.10.ps: bkcarta1.10.tex ASL_defs.tex
	$(TEXHOME)latex bkcarta1.10.tex && \
	$(TEXHOME)latex bkcarta1.10.tex && \
	$(TEXHOME)dvips -f bkcarta1.10.dvi > bkcarta1.10.ps

ReadMeFirst.ps: ReadMeFirst.tex ASL_defs.tex
	$(TEXHOME)latex ReadMeFirst.tex && \
	$(TEXHOME)latex ReadMeFirst.tex && \
	$(TEXHOME)dvips -f ReadMeFirst.dvi > ReadMeFirst.ps

kcarta1.09.ps: kcarta1.09.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.09.tex && \
	$(TEXHOME)latex kcarta1.09.tex && \
	$(TEXHOME)dvips -f kcarta1.09.dvi > kcarta1.09.ps

bkcarta1.09.ps: bkcarta1.09.tex ASL_defs.tex
	$(TEXHOME)latex bkcarta1.09.tex && \
	$(TEXHOME)latex bkcarta1.09.tex && \
	$(TEXHOME)dvips -f bkcarta1.09.dvi > bkcarta1.09.ps

kcarta1.08.ps: kcarta1.08.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.08.tex && \
	$(TEXHOME)latex kcarta1.08.tex && \
	$(TEXHOME)dvips -f kcarta1.08.dvi > kcarta1.08.ps

kcarta1.07.ps: kcarta1.07.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.07.tex && \
	$(TEXHOME)latex kcarta1.07.tex && \
	$(TEXHOME)dvips -f kcarta1.07.dvi > kcarta1.07.ps

kcarta1.06.ps: kcarta1.06.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.06.tex && \
	$(TEXHOME)latex kcarta1.06.tex && \
	$(TEXHOME)dvips -f kcarta1.06.dvi > kcarta1.06.ps

kcarta1.05.ps: kcarta1.05.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.05.tex && \
	$(TEXHOME)latex kcarta1.05.tex && \
	$(TEXHOME)dvips -f kcarta1.05.dvi > kcarta1.05.ps

kcarta1.04.ps: kcarta1.04.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.04.tex && \
	$(TEXHOME)latex kcarta1.04.tex && \
	$(TEXHOME)dvips -f kcarta1.04.dvi > kcarta1.04.ps

kcarta1.03.ps: kcarta1.03.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.03.tex && \
	$(TEXHOME)latex kcarta1.03.tex && \
	$(TEXHOME)dvips -f kcarta1.03.dvi > kcarta1.03.ps

kcarta1.02.ps: kcarta1.02.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.02.tex && \
	$(TEXHOME)latex kcarta1.02.tex && \
	$(TEXHOME)dvips -f kcarta1.02.dvi > kcarta1.02.ps

kcarta1.01.ps: kcarta1.01.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.01.tex && \
	$(TEXHOME)latex kcarta1.01.tex && \
	$(TEXHOME)dvips -f kcarta1.01.dvi > kcarta1.01.ps

kcarta1.00.ps: kcarta1.00.tex ASL_defs.tex
	$(TEXHOME)latex kcarta1.00.tex && \
	$(TEXHOME)latex kcarta1.00.tex && \
	$(TEXHOME)dvips -f kcarta1.00.dvi > kcarta1.00.ps

kcarta0.99.ps: kcarta0.99.tex ASL_defs.tex
	$(TEXHOME)latex kcarta0.99.tex && \
	$(TEXHOME)latex kcarta0.99.tex && \
	$(TEXHOME)dvips -f kcarta0.99.dvi > kcarta0.99.ps

kcarta0.98.ps: kcarta0.98.tex ASL_defs.tex
	$(TEXHOME)latex kcarta0.98.tex && \
	$(TEXHOME)latex kcarta0.98.tex && \
	$(TEXHOME)dvips -f kcarta0.98.dvi > kcarta0.98.ps

kcarta0.97.ps: kcarta0.97.tex ASL_defs.tex
	$(TEXHOME)latex kcarta0.97.tex && \
	$(TEXHOME)latex kcarta0.97.tex && \
	$(TEXHOME)dvips -f kcarta0.97.dvi > kcarta0.97.ps

readme0.97.ps: readme0.97.tex
	$(TEXHOME)latex readme0.97.tex && \
	$(TEXHOME)latex readme0.97.tex && \
	$(TEXHOME)dvips -f readme0.97.dvi > readme0.97.ps

kcarta0.96.ps: kcarta0.96.tex ASL_defs.tex
	$(TEXHOME)latex kcarta0.96.tex && \
	$(TEXHOME)latex kcarta0.96.tex && \
	$(TEXHOME)dvips -f kcarta0.96.dvi > kcarta0.96.ps

readme0.96.ps: readme0.96.tex
	$(TEXHOME)latex readme0.96.tex && \
	$(TEXHOME)latex readme0.96.tex && \
	$(TEXHOME)dvips -f readme0.96.dvi > readme0.96.ps

clean:
	rm *.aux *.lof *.dvi *.log *.lot *.toc *~ 2> /dev/null || true


