! DO NOT EDIT this file!!!!!!!

! kMaxLayer == number of kCompressed database press layers from Ground to Top
! kMaxPts   == max number of frequencies per kcomp block file
      INTEGER kMaxLayer,kMaxPts
      PARAMETER (kMaxLayer=100,kMaxPts=10000)

